### ISSUE TITLE
Floating-point NaN values shouldn't be hardcoded to 0xf97e00 without other options

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#86] opened 2020-01-03 16:42 UTC
From RFC 7049bis Draft 12:
>If NaN is an allowed value and there is no intent to support NaN
payloads or signaling NaNs, the protocol needs to pick a single
representation, for example 0xf97e00.

It's reasonable for specific protocols to choose 0xf97e00, but I don't think its practical for a generic CBOR library to make that decision for all protocols and all users.

Hard-coding 0xf97e00 result without any option to not to use 0xf97e00 creates problems:
* protocols that pick a different single representation of NaN can't use this library.
* protocols that support NaN payloads can't use this library.
* CBOR tests will fail with this library if they verify NaN payloads.  Whether they investigate further or instantly disqualify this library for being buggy is outside your control.

Some questions:
1.  Are there any generic CBOR libraries in any programming language that always encode NaN to 0xf97e00 without any other option?
2.  What are the benefits that is worth incurring the 3 problems?
3.  Even if you add options, is the default setting to encode NaN to 0xf97e00 the best choice?  Or should it default to converting the NaN payload just like hardware and software implementations of IEEE 754?

Whatever you decide, it should be documented under the Standards section or Limitations section.

**Comment by x448** [comment] 2020-01-03 19:55
@fxamacker thanks for pointing out Canonical CBOR requires 0xf97e00.

RFC 7049 (Oct 2013):
>If NaN is an allowed value, it must always be represented as 0xf97e00.

RFC 7049bis Draft 12 (Dec 2019) drops the word "must" regarding 0xf97e00 but it avoids changing the old definition of "Canonical CBOR" by using different terminology.

CTAP2 says:
> The representations of any floating-point values are not changed.

Given all this, here's my revised suggestion:
1. not urgent to add user-configurable options regarding floating-point NaN encoding but default behavior for NaN should be documented for all possible configurations
2. must not use 0xf97e00 encoding for all floating-point NaN with CTAP2 Canonical CBOR
3. must keep 0xf97e00 encoding for all floating-point NaN with Canonical CBOR
4. should keep 0xf97e00 encoding for all floating-point NaN with Core Deterministic but that entire configuration should be marked as "subject-to-change until 7049bis is approved"
5. with other configs (e.g. default), if user specifies ShortestFloatNone, ShortestFloat32, or ShortestFloat64, then don't convert any NaN to float16.  If user specifies ShortestFloat16 then you decide how the library should behave as default.

**Comment by x448** [comment] 2020-01-04 01:28
Summary of discussion:

Default encoding shouldn't change in v1, so it should continue encoding all floating-point NaN values to 0xf97e00 (CBOR type float16 [0xf9] = 0x7e00) and also ignore ShortestFloatMode.

For now, drop ShortestFloat32 and ShortestFloat64 options to simplify NaN conversion decisions and wrap up v1.5.

CTAP2 standards may have overlooked lossless encoding of infinity values to float16. So we'll add InfConvertMode to determine how to encode Inf and it will ignore ShortestFloatMode:

0.  InfConvertPreserveValue:  lossless encoding to IEEE binary16 (float16) since all values fit
1.  InfConvertNone:  never convert (used by CTAP2 Canonical CBOR but not a good idea)

NaNConvertMode will determine how to encode NaN and it will ignore ShortestFloatMode:

0. NaNConvertPredefined: always encode to 0xf97e00 (CBOR float16 = 0x7e00)
1. NaNConvertNone: never convert NaN to other representations (float64 NaN stays float64, etc.)
2. NaNConvertPreserveValue: if value fits, convert to smallest (preserve payload and quiet bit)
3. NaNConvertQuietWithPayload: always convert to float16 and force quiet bit = 1 

NaNConvertPredefined and NaNConvertNone are blockers for v1.5.   NaNConvertPreserveValue and NaNConvertQuietWithPayload will also be added if time allows this weekend.

Create separate ticket to add PreferredEncOptions() function to milestone v1.5.
Create separate ticket for NaNConvertMode for milestone v1.5.

**Comment by fxamacker** [comment] 2020-01-08 19:04
This issue is resolved by adding NaNConvert to EncOptions:

* NaNConvertNone: don't convert NaN to other representations -- used by CTAP2 Canonical CBOR.
* NaNConvert7e00: encode to 0xf97e00 (CBOR float16 = 0x7e00) -- used by RFC 7049 Canonical CBOR.
* NaNConvertQuiet: force quiet bit = 1 and use shortest form that preserves NaN payload.
* NaNConvertPreserveSignal: convert to smallest form that preserves value (quit bit unmodified and NaN payload preserved) -- described in RFC 7049bis Draft 12 when protocols don't want predifined value such as 0x7e00.

None of them are broken.  They all work as intended. :tada:

**Closed** 2020-01-09 02:26 UTC
