### ISSUE TITLE
cannot decode CBOR data with unknown structure containing map with []uint8 keys

### ISSUE THREAD

**Issue by agaffney** [fxamacker/cbor#312] opened 2021-12-20 03:30 UTC
### What version of fxamacker/cbor are you using?

`v2.3.0`

### Does this issue reproduce with the latest release?

Yes

### What OS and CPU architecture are you using (`go env`)?

`linux`/`amd64`

### What did you do?

I've encountered some CBOR in the wild (as part of Cardano testnet block data) that cannot be easily decoded using this library. The data defines a map with a bytestring (`[]uint8`) key, which Go generally does not allow and this library explicitly disallows it. The data does not have a predefined structure, so I can't easily work around this by mapping it to a `map[string]...` via a `struct`.

The data in question can be found at this [`cbor.me` link](https://tinyurl.com/2p94ec7r)

### What did you expect to see?

A successful decode

### What did you see instead?

`cbor: invalid map key type: []uint8`

**Comment by agaffney** [comment] 2021-12-20 03:32
I wouldn't exactly call this a bug, but it's also not quite a feature request. I don't have a good suggestion for how to handle this use case.

**Comment by fxamacker** [comment] 2021-12-20 04:17
Thanks for reporting this.

> I wouldn't exactly call this a bug, but it's also not quite a feature request.

Yea, me too.  It's not a bug because Go doesn't allow []uint8 as map key.

>  I don't have a good suggestion for how to handle this use case.

Hmm, I need to think about it some more when time allows so I'll leave this open.  There are some possibilities but they might turn out to be bad ideas.

**Comment by agaffney** [comment] 2021-12-20 04:30
It seems that an array with a fixed length (vs. a slice) can be used as a map key in Go, so perhaps creating the map as `map[[7]uint8]...` in cases where the array length is known (and consistent) could be a viable workaround. That seems awfully niche, though.

**Comment by agaffney** [comment] 2021-12-29 22:44
As a workaround, I was able to define the structure far enough to create an empty `UnmarshalCBOR()` function for this particular part of the data to just "ignore" it. It's not ideal, but I can live with it for now.

The other part is trying to figure out which set of data structures to use for a given chunk of CBOR to allow this workaround to actually work, which is the focus of #317

**Comment by agaffney** [comment] 2022-01-20 01:33
How would you feel about a decoder flag to enable optional behavior to encode a byte string map key using either `string` or a hex encoded string representation (only when the destination is a `interface{}`)? I can take a crack at implementing something like that.

**Comment by fxamacker** [comment] 2022-01-22 17:25
I have some new features planned for a future release (v2.5 or v2.6) that might be useful in resolving some or all of this issue. 

> How would you feel about a decoder flag to enable optional behavior to encode a byte string map key using either string or a hex encoded string representation (only when the destination is a interface{})? I can take a crack at implementing something like that.

I understand why this approach is being considered.  However, some aspects of it might introduce edge cases that could be problematic for round-trip encoding/decoding. For example, CBOR text string requires valid UTF-8 strings.

**Comment by agaffney** [comment] 2022-01-22 17:41
I started work on an attempt to address this in a fork last night. I'm using a `struct` instead of just using a `string` (but it's still using a `string` internally so that the struct is still comparable), so it will be easier to handle the round trip edge cases. I hope to have something working this weekend.

**Comment by agaffney** [comment] 2022-01-22 19:58
What are the features that you have planned for 2.5/2.6? All I really need is the ability to parse CBOR that contains map with bytestring keys without having to predefine the structures. It's not that important to me what form that parsed bytestring takes, as long as the CBOR can be parsed and I can access the original bytestring data.

**Comment by agaffney** [comment] 2022-01-23 00:54
I created PR #319 with my proposed fix for this issue. However, it cannot currently run the CI workflows due to me being a first-time contributor and it needing approval

**Comment by agaffney** [comment] 2022-12-05 00:06
I ended up closing the PR due to apparent lack of interest, but I created a wrapper object that can use the `ByteString` type from #319 when parsing arbitrary CBOR in order to solve my problem. This can be seen in cloudstruct/go-cardano-ledger#16

**Closed** 2022-12-29 23:32 UTC
Labels: not a bug
