### ISSUE TITLE
How to convert CBOR to JSON

### ISSUE THREAD

**Issue by kant777** [fxamacker/cbor#505] opened 2024-03-12 01:50 UTC
I have a cbor byte slice and I need to convert that to json string but it fails with an error

```
var data interface{}
cbor.unmarsha(abi, &data) //abi is in cbor and the underlying data is array of objects
json.Marshal(data)
```

I get the error 

```
unsupported type : map[interface{}] interface{}
```

**Comment by x448** [comment] 2024-03-17 19:37
@fxamaacker This seems to be a non-CBOR question about how to use `encoding/json` package when it fails to encode unsupported data types.

- The reported error message left out "json: " prefix.  The actual error message is:  
  > "json: unsupported type: map[interface {}]interface {}."
- The example code doesn't compile.

Here's a simple reproducer that compiles without involving this library:

```Go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	data := make(map[interface{}]interface{}, 0)
	_, err := json.Marshal(data)
	if err != nil {
		fmt.Printf("%s\n", err)
		return
	}
}
```

The reproducer shows the problem doesn't involve this library.  They need to decide how to use their JSON encoder or `encoding/json` to encode unsupported Go data types like `map[interface{}]interface{}`.

**Comment by fxamacker** [comment] 2024-03-17 20:53
Hi @kant777, thanks for opening this issue.

You can use `cbor.DefaultMapType` decoding option to resolve the issue you described.  

Docs:
```Go
// DefaultMapType specifies Go map type to create and decode to
// when unmarshalling CBOR into an empty interface value.
// By default, unmarshal uses map[interface{}]interface{}.
DefaultMapType reflect.Type
```
Snippet:
```Go
myDecMode, err := cbor.DecOptions{
        DefaultMapType: reflect.TypeOf(map[string]interface{}(nil)),  // compatible with JSON
    }.DecMode()

err := myDecMode.Unmarshal(abi, &data)
```

Example program:  https://go.dev/play/p/_H00A18NzSs 

Please let me know if it works for you.

### Details

<details><summary>More details... :mag: </summary><p/>

As @x448 mentioned, `json.Marshal()` returns `json.UnsupportedTypeError` when encoding a value of `map[interface{}]interface{}` type.  Using `cbor.DefaultMapType` option as shown above will make it compatible with JSON encoders.

In your example,
- when `cbor.Umarshal()` decodes CBOR map into a value of empty interface type (`var data interface{}`), decoded value is created as `map[interface{}]interface{}` to allow decoding heterogeneous map.
- `json.Marshal()` returns  `json.UnsupportedTypeError` because it rejects map value with `interface{}` as map key (See [code](https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/encoding/json/encode.go;l=767) in encoding/json for more details)

Please try this code snippet:
```Go
// NOTE: error handling omitted to simplify example code

decMode, _ := cbor.DecOptions{
	DefaultMapType: reflect.TypeOf(map[string]interface{}(nil)),
}.DecMode()

abi := []byte{0x82, 0xa2, 0x61, 0x61, 0x01, 0x61, 0x62, 0x02, 0xa2, 0x61, 0x63, 0x03, 0x61, 0x64, 0x04} // [{"a": 1, "b": 2}, {"c": 3, "d": 4}]
var data interface{}
_ = decMode.Unmarshal(abi, &data) //abi is in cbor and the underlying data is array of objects
s, _ := json.Marshal(data)	

fmt.Printf("json: %s\n", string(s))	
// Output: json: [{"a":1,"b":2},{"c":3,"d":4}]
```
Complete example program:  https://go.dev/play/p/_H00A18NzSs 

</details>

**Comment by fxamacker** [comment] 2024-04-01 01:08
Closing this issue as resolved/answered.  Please feel free to reopen if anything was missed.

**Closed by fxamacker** 2024-04-01 01:08 UTC
